SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `retaguarda_agendamento` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE SCHEMA IF NOT EXISTS `agenda_operacional` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `retaguarda_agendamento`;

CREATE TABLE IF NOT EXISTS `SCHEMA_MIGRATION` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `VERSION` VARCHAR(30) NOT NULL,
  `FILE_NAME` VARCHAR(255) NOT NULL,
  `CHECKSUM_SHA256` VARCHAR(64) NOT NULL,
  `APPLIED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_SCHEMA_MIGRATION_VERSION` (`VERSION`),
  UNIQUE KEY `UK_SCHEMA_MIGRATION_FILE` (`FILE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EMPRESA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RAZAO_SOCIAL` VARCHAR(150) NULL,
  `NOME_FANTASIA` VARCHAR(150) NULL,
  `CNPJ` VARCHAR(14) NULL,
  `INSCRICAO_ESTADUAL` VARCHAR(30) NULL,
  `INSCRICAO_MUNICIPAL` VARCHAR(30) NULL,
  `TIPO_REGIME` CHAR(1) NULL,
  `CRT` CHAR(1) NULL,
  `DATA_CONSTITUICAO` DATE NULL,
  `TIPO` CHAR(1) NULL,
  `EMAIL` VARCHAR(250) NULL,
  `LOGRADOURO` VARCHAR(250) NULL,
  `NUMERO` VARCHAR(10) NULL,
  `COMPLEMENTO` VARCHAR(100) NULL,
  `CEP` VARCHAR(8) NULL,
  `BAIRRO` VARCHAR(100) NULL,
  `CIDADE` VARCHAR(100) NULL,
  `UF` CHAR(2) NULL,
  `FONE` VARCHAR(15) NULL,
  `CONTATO` VARCHAR(30) NULL,
  `CODIGO_IBGE_CIDADE` INT UNSIGNED NULL,
  `CODIGO_IBGE_UF` INT UNSIGNED NULL,
  `LOGOTIPO` TEXT NULL,
  `REGISTRADO` CHAR(1) NULL DEFAULT 'P',
  `NATUREZA_JURIDICA` VARCHAR(200) NULL,
  `SIMEI` CHAR(1) NULL,
  `EMAIL_PAGAMENTO` VARCHAR(250) NULL,
  `DATA_REGISTRO` DATE NULL,
  `HORA_REGISTRO` VARCHAR(8) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_EMPRESA_CNPJ` (`CNPJ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `RET_USUARIO` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `NOME` VARCHAR(150) NULL,
  `LOGIN` VARCHAR(80) NOT NULL,
  `EMAIL` VARCHAR(180) NULL,
  `SENHA_HASH` VARCHAR(128) NOT NULL,
  `SENHA_SALT` VARCHAR(64) NOT NULL,
  `PERFIL` VARCHAR(30) NOT NULL DEFAULT 'Administrador',
  `CONFIRMADO` CHAR(1) NOT NULL DEFAULT 'P',
  `CONFIRMADO_EM` DATETIME NULL,
  `ATIVO` CHAR(1) NOT NULL DEFAULT 'S',
  `CRIADO_EM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ULTIMO_LOGIN` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_RET_USUARIO_EMPRESA_LOGIN` (`ID_EMPRESA`, `LOGIN`),
  UNIQUE KEY `UK_RET_USUARIO_EMAIL` (`EMAIL`),
  CONSTRAINT `FK_RET_USUARIO_EMPRESA`
    FOREIGN KEY (`ID_EMPRESA`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `RET_SESSAO` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT UNSIGNED NOT NULL,
  `TOKEN_HASH` VARCHAR(128) NOT NULL,
  `CRIADO_EM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EXPIRA_EM` DATETIME NOT NULL,
  `REVOGADO` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_RET_SESSAO_TOKEN` (`TOKEN_HASH`),
  CONSTRAINT `FK_RET_SESSAO_USUARIO`
    FOREIGN KEY (`ID_USUARIO`) REFERENCES `RET_USUARIO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `RET_EMAIL_TOKEN` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT UNSIGNED NOT NULL,
  `TIPO` VARCHAR(40) NOT NULL,
  `TOKEN_HASH` VARCHAR(128) NOT NULL,
  `CRIADO_EM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EXPIRA_EM` DATETIME NOT NULL,
  `USADO_EM` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `IX_RET_EMAIL_TOKEN_USUARIO_TIPO` (`ID_USUARIO`, `TIPO`),
  INDEX `IX_RET_EMAIL_TOKEN_HASH` (`TOKEN_HASH`),
  CONSTRAINT `FK_RET_EMAIL_TOKEN_USUARIO`
    FOREIGN KEY (`ID_USUARIO`) REFERENCES `RET_USUARIO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

USE `agenda_operacional`;

CREATE TABLE IF NOT EXISTS `AGENDA_SYNC_EXECUCAO` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `DISPOSITIVO_ID` VARCHAR(64) NOT NULL,
  `INICIADO_EM` DATETIME NOT NULL,
  `FINALIZADO_EM` DATETIME NULL,
  `TOTAL_TABELAS` INT NOT NULL DEFAULT 0,
  `TOTAL_REGISTROS` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `IX_AGENDA_SYNC_EXECUCAO_EMPRESA` (`ID_EMPRESA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AGENDA_SYNC_REGISTRO` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EXECUCAO` BIGINT UNSIGNED NOT NULL,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `TABELA` VARCHAR(128) NOT NULL,
  `ID_LOCAL` VARCHAR(128) NOT NULL,
  `DISPOSITIVO_ID` VARCHAR(64) NOT NULL,
  `DADOS_JSON` LONGTEXT NOT NULL,
  `HASH_SHA256` VARCHAR(64) NOT NULL,
  `SINCRONIZADO_EM` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AGENDA_SYNC_REGISTRO_TENANT_TABELA_ID_DEVICE` (`ID_EMPRESA`, `TABELA`, `ID_LOCAL`, `DISPOSITIVO_ID`),
  INDEX `IX_AGENDA_SYNC_REGISTRO_EXECUCAO` (`ID_EXECUCAO`),
  INDEX `IX_AGENDA_SYNC_REGISTRO_EMPRESA` (`ID_EMPRESA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AGENDA_SYNC_CONFLITO` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `TABELA` VARCHAR(128) NOT NULL,
  `ID_LOCAL` VARCHAR(128) NOT NULL,
  `DISPOSITIVO_ID` VARCHAR(64) NOT NULL,
  `DADOS_LOCAL` LONGTEXT NULL,
  `DADOS_REMOTO` LONGTEXT NULL,
  `MOTIVO` VARCHAR(500) NULL,
  `STATUS` VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
  `CRIADO_EM` DATETIME NOT NULL,
  `RESOLVIDO_EM` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `IX_AGENDA_SYNC_CONFLITO_EMPRESA` (`ID_EMPRESA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AGENDA_DISPOSITIVO` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `DISPOSITIVO_ID` VARCHAR(64) NOT NULL,
  `NOME` VARCHAR(120) NULL,
  `ULTIMA_SINCRONIZACAO_EM` DATETIME NULL,
  `ATIVO` CHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AGENDA_DISPOSITIVO_EMPRESA_DISPOSITIVO` (`ID_EMPRESA`, `DISPOSITIVO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AGENDA_AUDITORIA_OPERACIONAL` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `TABELA` VARCHAR(128) NOT NULL,
  `ID_LOCAL` VARCHAR(128) NOT NULL,
  `DISPOSITIVO_ID` VARCHAR(64) NOT NULL,
  `ACAO` VARCHAR(30) NOT NULL,
  `DADOS_JSON` LONGTEXT NULL,
  `CRIADO_EM` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `IX_AGENDA_AUDITORIA_EMPRESA_TABELA` (`ID_EMPRESA`, `TABELA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `INTEGRACAO_OUTBOX` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `ORIGEM` VARCHAR(60) NOT NULL,
  `ENTIDADE` VARCHAR(128) NOT NULL,
  `ID_LOCAL` VARCHAR(128) NOT NULL,
  `PAYLOAD_JSON` LONGTEXT NOT NULL,
  `STATUS` VARCHAR(30) NOT NULL DEFAULT 'PROCESSADO',
  `CRIADO_EM` DATETIME NOT NULL,
  `PROCESSADO_EM` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `IX_INTEGRACAO_OUTBOX_EMPRESA_STATUS` (`ID_EMPRESA`, `STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `INTEGRACAO_CONFLITO` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `ENTIDADE` VARCHAR(128) NOT NULL,
  `ID_LOCAL` VARCHAR(128) NOT NULL,
  `MOTIVO` VARCHAR(500) NULL,
  `PAYLOAD_JSON` LONGTEXT NULL,
  `STATUS` VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
  `CRIADO_EM` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `IX_INTEGRACAO_CONFLITO_EMPRESA` (`ID_EMPRESA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `INTEGRACAO_LOG` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` INT UNSIGNED NOT NULL,
  `ENTIDADE` VARCHAR(128) NOT NULL,
  `ID_LOCAL` VARCHAR(128) NULL,
  `EVENTO` VARCHAR(60) NOT NULL,
  `MENSAGEM` VARCHAR(1000) NULL,
  `CRIADO_EM` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `IX_INTEGRACAO_LOG_EMPRESA` (`ID_EMPRESA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Usuario dedicado da API para o modulo de sincronizacao (a AdminConnection nao usa root).
CREATE USER IF NOT EXISTS 'agenda_admin'@'%' IDENTIFIED BY 'AgendaAdmin@2026';
GRANT ALL PRIVILEGES ON `agenda_operacional`.* TO 'agenda_admin'@'%';
GRANT SELECT, UPDATE ON `retaguarda_agendamento`.`EMPRESA` TO 'agenda_admin'@'%';
FLUSH PRIVILEGES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
